-- =====================================================================
-- DanzaCheck - esquema de la base de datos
--
-- Refleja exactamente las entidades JPA del backend
-- (SesionAsistencia y Asistencia), por eso se puede desplegar con
-- DDL_AUTO=validate sin que Hibernate reclame diferencias.
--
-- Como aplicarlo (una sola vez, sobre el proyecto de Supabase):
--   1. Abrir el proyecto en el panel de Supabase.
--   2. Pegar este archivo en el SQL Editor y ejecutarlo.
--   3. Después aplicar 02-row-level-security.sql.
--
-- A partir de aqui el esquema se considera definitive: los cambios
-- posteriores se hacen aqui y se vuelven a aplicar a mano, no con
-- ddl-auto=update, porque en produccion el backend solo valida.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Sesion de ensayo.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sesion_asistencia (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(120) NOT NULL,
    fecha       DATE NOT NULL,
    hora_inicio TIME(6) NOT NULL,
    hora_fin    TIME(6),
    -- El codigo es publico: es lo que los alumnos teclean para apuntarse.
    -- No se basa en el id, asi que puede tener la forma que el backend
    -- quiera sin exponer la cantidad de sesiones creadas.
    codigo      VARCHAR(12) NOT NULL,
    activa      BOOLEAN NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_sesion_asistencia_codigo UNIQUE (codigo)
);

COMMENT ON TABLE sesion_asistencia IS
    'Sesion de ensayo. El codigo publico permite registrarse sin cuenta.';

-- ---------------------------------------------------------------------
-- Asistencia de un alumno a una sesion.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS asistencia (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(120) NOT NULL,
    correo     VARCHAR(254) NOT NULL,
    fecha_hora TIMESTAMP(6) NOT NULL,
    sesion_id  BIGINT NOT NULL,
    -- Ultima linea de defensa contra duplicados: el backend tambien
    -- valida, pero si dos peticiones llegan a la vez la restriccion
    -- unica es la que rechaza la segunda.
    CONSTRAINT uk_asistencia_sesion_correo UNIQUE (sesion_id, correo),
    -- CASCADE: al borrar una sesión se van sus asistencias. Es la regla que
    -- espera el panel cuando alguien elimina una sesión de prueba, y evita
    -- que queden asistencias apuntando a una sesión que ya no existe.
    CONSTRAINT fk_asistencia_sesion FOREIGN KEY (sesion_id)
        REFERENCES sesion_asistencia (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_asistencia_sesion ON asistencia (sesion_id);

COMMENT ON TABLE asistencia IS
    'Asistencia de un alumno. El correo se normaliza a minusculas antes de guardar.';

COMMIT;
